const dataColors = {
	primitive: "#F8F7F2",
	relational: "#8FD694",
	storage: "#5BC0EB",
	optimizer: "#FDE74C",
	semantic: "#C084FC",
	visual: "#FF6B6B",
	execution: "#A7F3D0",
}

function layerPoints(layer) {
	if (!player[layer]) return new Decimal(0)
	return player[layer].points
}

function makeAnalyticsLayer(config) {
	let upgrades = {}
	if (config.upgradeTitle) {
		upgrades[11] = {
			title: config.upgradeTitle,
			description: config.upgradeDescription,
			cost: config.upgradeCost || new Decimal(1),
			effect() {
				return player[this.layer].points.add(1).ln().add(1).pow(config.upgradePower || 1)
			},
			effectDisplay() {return format(this.effect()) + "x"},
		}
	}

	let buyables = {}
	if (config.buyableTitle) {
		buyables[11] = {
			title: config.buyableTitle,
			cost(x) {
				return Decimal.pow(config.buyableBase || 2, x.add(1)).times(config.buyableCost || 1).floor()
			},
			effect(x) {
				return x.add(1).pow(config.buyablePower || 1)
			},
			display() {
				return "You have " + getBuyableAmount(this.layer, this.id) + " " + config.buyableResource
					+ "<br><br>Effect: " + format(buyableEffect(this.layer, this.id)) + "x"
					+ "<br><br>Cost: " + format(tmp[this.layer].buyables[this.id].cost) + " " + tmp[this.layer].resource
			},
			canAfford() {
				return player[this.layer].points.gte(tmp[this.layer].buyables[this.id].cost)
			},
			buy() {
				let cost = tmp[this.layer].buyables[this.id].cost
				player[this.layer].points = player[this.layer].points.sub(cost)
				setBuyableAmount(this.layer, this.id, getBuyableAmount(this.layer, this.id).add(1))
			},
		}
	}

	addLayer(config.id, {
		name: config.name,
		symbol: config.symbol,
		position: config.position,
		startData() { return {
			unlocked: true,
			points: new Decimal(0),
			best: new Decimal(0),
			total: new Decimal(0),
		}},
		color: config.color,
		requires: config.requires,
		resource: config.resource,
		baseResource: config.baseResource,
		baseAmount: config.baseAmount,
		type: config.type || "normal",
		exponent: config.exponent || 0.5,
		gainMult() {
			let mult = new Decimal(1)
			if (config.boostedBy) {
				for (let index = 0; index < config.boostedBy.length; index++) {
					mult = mult.times(layerPoints(config.boostedBy[index]).add(1))
				}
			}
			if (config.buyableTitle) mult = mult.times(buyableEffect(this.layer, 11))
			if (config.upgradeTitle && hasUpgrade(this.layer, 11)) mult = mult.times(upgradeEffect(this.layer, 11))
			return mult
		},
		gainExp() {
			return new Decimal(1)
		},
		effect() {
			let effect = player[this.layer].points.add(1).ln().add(1).pow(config.effectPower || 1)
			if (config.buyableTitle) effect = effect.times(buyableEffect(this.layer, 11))
			return effect
		},
		effectDescription() {
			return config.effectDescription + " by " + format(tmp[this.layer].effect) + "x"
		},
		row: config.row,
		branches: config.branches,
		layerShown() {return true},
		tooltip() {
			return formatWhole(player[this.layer].points) + " " + this.resource
		},
		tabFormat: [
			"main-display",
			["display-text", config.effectDescription + "."],
			["blank", "8px"],
			"prestige-button",
			"resource-display",
			["blank", "12px"],
			["display-text", config.definition],
			["blank", "12px"],
			["display-text", config.flavor],
			["blank", "12px"],
			"buyables",
			["blank", "12px"],
			"upgrades",
			["blank", "12px"],
			"milestones",
		],
		upgrades,
		buyables,
		milestones: {
			0: {
				requirementDescription: formatWhole(config.milestoneAt || 5) + " " + config.resource,
				effectDescription: config.milestoneText,
				done() {return player[this.layer].best.gte(config.milestoneAt || 5)},
			},
		},
		hotkeys: config.hotkey ? [
			{
				key: config.hotkey,
				description: config.hotkey.toUpperCase() + ": reset for " + config.resource,
				onPress(){if (canReset(this.layer)) doReset(this.layer)},
			},
		] : [],
	})
}

makeAnalyticsLayer({
	id: "tup",
	name: "Tuple",
	symbol: "Tup",
	position: 0,
	row: 0,
	color: dataColors.primitive,
	requires: new Decimal(10),
	resource: "typed tuples",
	baseResource: "events",
	baseAmount() {return player.points},
	boostedBy: ["rel", "alg", "stat", "viz", "simd"],
	definition: "A tuple is a typed row: values, attribute names, nullability, and enough shape to enter relational systems.",
	flavor: "Raw events become rows once ingestion assigns types, timestamps, identifiers, and failure modes.",
	effectDescription: "These typed tuples multiply event ingress",
	upgradeTitle: "Schema-on-Write",
	upgradeDescription: "Validate fields during ingestion instead of rediscovering malformed events in every downstream query.",
	upgradeCost: new Decimal(3),
	buyableTitle: "Empty Rows",
	buyableResource: "empty rows",
	buyableBase: 2,
	buyablePower: 0.75,
	milestoneAt: 10,
	milestoneText: "The warehouse admits that nullability is a social construct.",
	hotkey: "t",
})

makeAnalyticsLayer({
	id: "rel",
	name: "Relation",
	symbol: "Rel",
	position: 0,
	row: 1,
	color: dataColors.storage,
	requires: new Decimal(4),
	resource: "relations",
	baseResource: "typed tuples",
	baseAmount() {return layerPoints("tup")},
	boostedBy: ["sch", "stat"],
	branches: ["tup"],
	definition: "A relation is a set of tuples over named attributes, the formal core behind tables and query results.",
	flavor: "Codd removes physical row order and leaves keys, dependencies, joins, projection, and a lot of useful discipline.",
	effectDescription: "Relations multiply tuple normalization",
	upgradeTitle: "First Normal Form",
	upgradeDescription: "Ban nested attributes until the BI tool invents JSON columns again.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Candidate Keys",
	buyableResource: "candidate keys",
	buyableBase: 2.25,
	buyablePower: 0.8,
	milestoneAt: 8,
	milestoneText: "Projection and selection become first-class operations instead of spreadsheet habits.",
	hotkey: "r",
})

makeAnalyticsLayer({
	id: "sch",
	name: "Schema",
	symbol: "Sch",
	position: 0,
	row: 2,
	color: dataColors.storage,
	requires: new Decimal(3),
	resource: "schemas",
	baseResource: "relations",
	baseAmount() {return layerPoints("rel")},
	boostedBy: ["cat", "onto"],
	branches: ["rel"],
	definition: "A schema names relations, columns, data types, constraints, indexes, and ownership boundaries.",
	flavor: "DDL is where product assumptions become production contracts.",
	effectDescription: "Schemas multiply relation materialization",
	upgradeTitle: "Foreign Key Constraints",
	upgradeDescription: "Make relationships explicit enough for integrity checks, joins, and modeling tools to trust them.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Check Constraints",
	buyableResource: "check constraints",
	buyableBase: 2,
	buyablePower: 1.1,
	milestoneAt: 6,
	milestoneText: "Dimension tables become reusable instead of being rebuilt in every dashboard.",
	hotkey: "s",
})

makeAnalyticsLayer({
	id: "cat",
	name: "Catalog",
	symbol: "Catlg",
	position: 0,
	row: 3,
	color: dataColors.storage,
	requires: new Decimal(2),
	resource: "catalogs",
	baseResource: "schemas",
	baseAmount() {return layerPoints("sch")},
	boostedBy: ["db"],
	branches: ["sch", "stat"],
	definition: "A catalog stores metadata about schemas, tables, columns, indexes, statistics, privileges, and lineage.",
	flavor: "Catalog data is operational: query planners, governance tools, and BI explorers all depend on it.",
	effectDescription: "Catalogs multiply schema discovery",
	upgradeTitle: "Information Schema",
	upgradeDescription: "Expose standard metadata views so tools can discover tables without hand-maintained config.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Statistics Objects",
	buyableResource: "statistics objects",
	buyableBase: 2.5,
	buyablePower: 1,
	milestoneAt: 4,
	milestoneText: "The data dictionary becomes complete enough for humans and planners to use.",
	hotkey: "c",
})

makeAnalyticsLayer({
	id: "db",
	name: "Database",
	symbol: "DB",
	position: 0,
	row: 4,
	color: dataColors.storage,
	requires: new Decimal(2),
	resource: "databases",
	baseResource: "catalogs",
	baseAmount() {return layerPoints("cat")},
	boostedBy: ["exec"],
	branches: ["cat"],
	definition: "A database combines logical models with storage, transactions, indexes, catalogs, and execution engines.",
	flavor: "Relations are clean; databases add pages, locks, WAL, compaction, memory pressure, and operational reality.",
	effectDescription: "Databases multiply the whole storage spine",
	upgradeTitle: "MVCC Snapshots",
	upgradeDescription: "Serve consistent reads while writes continue, with vacuum debt waiting in the background.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Buffer Pages",
	buyableResource: "buffer pages",
	buyableBase: 3,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "Operational constraints now matter as much as logical correctness.",
	hotkey: "d",
})

makeAnalyticsLayer({
	id: "alg",
	name: "Relational Algebra",
	symbol: "RA",
	position: -2,
	row: 1,
	color: dataColors.relational,
	requires: new Decimal(4),
	resource: "algebra terms",
	baseResource: "typed tuples",
	baseAmount() {return layerPoints("tup")},
	boostedBy: ["qry", "opt"],
	branches: ["tup"],
	definition: "Relational algebra composes selection, projection, joins, union, difference, aggregation, and renaming.",
	flavor: "SQL gets lowered into algebra so equivalence rules can simplify and reorder work.",
	effectDescription: "Algebra terms multiply tuple rewriting",
	upgradeTitle: "Rename Operator",
	upgradeDescription: "Track attribute names through derived relations so later joins do not become ambiguous.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Join Trees",
	buyableResource: "join trees",
	buyableBase: 2.2,
	buyablePower: 0.9,
	milestoneAt: 8,
	milestoneText: "Selection pushdown removes rows before the expensive operators see them.",
	hotkey: "a",
})

makeAnalyticsLayer({
	id: "qry",
	name: "Query",
	symbol: "SQL",
	position: -2,
	row: 2,
	color: dataColors.relational,
	requires: new Decimal(3),
	resource: "queries",
	baseResource: "algebra terms",
	baseAmount() {return layerPoints("alg")},
	boostedBy: ["opt", "ds"],
	branches: ["alg"],
	definition: "A query describes the result relation while leaving access paths, join order, and physical operators open.",
	flavor: "The SELECT list reads like intent; the FROM clause determines whether the system has a long afternoon.",
	effectDescription: "Queries multiply algebra lowering",
	upgradeTitle: "Correlated Subquery",
	upgradeDescription: "Reference outer rows from inner expressions and give the optimizer a decorrelation problem.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Common Table Expressions",
	buyableResource: "CTEs",
	buyableBase: 2,
	buyablePower: 1,
	milestoneAt: 6,
	milestoneText: "Recursive CTEs become a sanctioned fixed point.",
	hotkey: "q",
})

makeAnalyticsLayer({
	id: "stat",
	name: "Table Statistics",
	symbol: "Stats",
	position: -1,
	row: 1,
	color: dataColors.optimizer,
	requires: new Decimal(4),
	resource: "histograms",
	baseResource: "typed tuples",
	baseAmount() {return layerPoints("tup")},
	boostedBy: ["cat", "opt"],
	branches: ["tup"],
	definition: "Table statistics summarize cardinality, value distributions, null fractions, correlation, and data skew.",
	flavor: "Histograms, most-common values, and distinct-count estimates are small summaries with large consequences.",
	effectDescription: "Histograms multiply tuple sampling",
	upgradeTitle: "NDV Estimator",
	upgradeDescription: "Count distinct values by not counting most of them.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Most Common Values",
	buyableResource: "MCV buckets",
	buyableBase: 2,
	buyablePower: 1.15,
	milestoneAt: 8,
	milestoneText: "The planner stops assuming uniform distributions for obviously skewed columns.",
	hotkey: "h",
})

makeAnalyticsLayer({
	id: "opt",
	name: "Query Optimizer",
	symbol: "Opt",
	position: -2,
	row: 3,
	color: dataColors.optimizer,
	requires: new Decimal(2),
	resource: "plans",
	baseResource: "queries",
	baseAmount() {return layerPoints("qry")},
	boostedBy: ["stat", "exec"],
	branches: ["qry", "stat"],
	definition: "A query optimizer searches equivalent logical plans and chooses physical operators using estimated cost.",
	flavor: "Dynamic programming, cardinality estimates, access paths, bushy joins, and one catastrophic nested loop.",
	effectDescription: "Plans multiply query execution",
	upgradeTitle: "Volcano Memo",
	upgradeDescription: "Memoize equivalent expressions so cost-based search can compare alternatives directly.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Join Reorderings",
	buyableResource: "join reorderings",
	buyableBase: 2.75,
	buyablePower: 1.05,
	milestoneAt: 4,
	milestoneText: "The optimizer learns to fear cross joins.",
	hotkey: "o",
})

makeAnalyticsLayer({
	id: "ds",
	name: "Data Set",
	symbol: "DS",
	position: -1,
	row: 3,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "data sets",
	baseResource: "queries",
	baseAmount() {return layerPoints("qry")},
	boostedBy: ["onto", "viz"],
	branches: ["qry"],
	definition: "A data set is a governed query result with lineage, freshness, owners, documentation, and consumers.",
	flavor: "It is not just a table; it is a reusable contract for downstream analytics.",
	effectDescription: "Data sets multiply query reuse",
	upgradeTitle: "Column Lineage",
	upgradeDescription: "Trace output fields back through transforms so ownership and impact analysis are possible.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Materializations",
	buyableResource: "materializations",
	buyableBase: 2.25,
	buyablePower: 1.1,
	milestoneAt: 4,
	milestoneText: "Freshness SLAs become visible enough to be enforced.",
	hotkey: "x",
})

makeAnalyticsLayer({
	id: "onto",
	name: "Business Ontology",
	symbol: "Biz",
	position: -1,
	row: 4,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "business concepts",
	baseResource: "data sets",
	baseAmount() {return layerPoints("ds")},
	boostedBy: ["sem"],
	branches: ["ds", "sch"],
	definition: "A business ontology names entities, events, measures, dimensions, ownership, and allowed relationships.",
	flavor: "Customer, account, booking, revenue, churn, active user: each term needs a definition before the chart does.",
	effectDescription: "Business concepts multiply semantic compilation",
	upgradeTitle: "Entity Resolution",
	upgradeDescription: "Connect source-system identifiers into stable business entities before metrics depend on them.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Metric Definitions",
	buyableResource: "metric definitions",
	buyableBase: 2.5,
	buyablePower: 1.25,
	milestoneAt: 3,
	milestoneText: "The model starts rejecting contradictory KPI definitions.",
	hotkey: "l",
})

makeAnalyticsLayer({
	id: "sem",
	name: "Semantic Layer",
	symbol: "Sem",
	position: -1,
	row: 5,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "semantic layers",
	baseResource: "business concepts",
	baseAmount() {return layerPoints("onto")},
	boostedBy: ["dash"],
	branches: ["onto"],
	definition: "A semantic layer exposes governed metrics, dimensions, permissions, and SQL generation across tools.",
	flavor: "It turns agreed business definitions into reusable queries for dashboards, notebooks, and APIs.",
	effectDescription: "Semantic layers multiply dashboard correctness",
	upgradeTitle: "Metric Contract",
	upgradeDescription: "Define grain, filters, owners, allowed dimensions, and freshness expectations for each measure.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Business Terms",
	buyableResource: "business terms",
	buyableBase: 2,
	buyablePower: 1.35,
	milestoneAt: 3,
	milestoneText: "Self-service analytics briefly means what it says.",
	hotkey: "m",
})

makeAnalyticsLayer({
	id: "viz",
	name: "Visualization Grammar",
	symbol: "Viz",
	position: 1,
	row: 1,
	color: dataColors.visual,
	requires: new Decimal(4),
	resource: "marks",
	baseResource: "typed tuples",
	baseAmount() {return layerPoints("tup")},
	boostedBy: ["panel", "dash"],
	branches: ["tup"],
	definition: "A visualization grammar maps fields to marks, channels, scales, guides, facets, transforms, and layouts.",
	flavor: "Vega-Lite, ggplot, and similar grammars make chart construction explicit enough to reason about.",
	effectDescription: "Marks multiply visual encoding",
	upgradeTitle: "Grammar of Graphics",
	upgradeDescription: "Separate data, encodings, marks, statistical transforms, scales, coordinates, and guides.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Scales",
	buyableResource: "scales",
	buyableBase: 2,
	buyablePower: 0.95,
	milestoneAt: 8,
	milestoneText: "Axes stop lying unless explicitly configured to lie.",
	hotkey: "v",
})

makeAnalyticsLayer({
	id: "panel",
	name: "Panel",
	symbol: "Panel",
	position: 1,
	row: 3,
	color: dataColors.visual,
	requires: new Decimal(2),
	resource: "panels",
	baseResource: "marks",
	baseAmount() {return layerPoints("viz")},
	boostedBy: ["dash"],
	branches: ["viz", "ds"],
	definition: "A panel combines one visual, its query, thresholds, filters, title, layout, and interaction state.",
	flavor: "Panel design is where chart grammar meets dashboard review, alert thresholds, and limited screen space.",
	effectDescription: "Panels multiply mark composition",
	upgradeTitle: "Small Multiples",
	upgradeDescription: "Repeat the same visual across dimension values for comparison without changing encodings.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Encodings",
	buyableResource: "encodings",
	buyableBase: 2.4,
	buyablePower: 1.15,
	milestoneAt: 4,
	milestoneText: "Tooltips acquire a type system.",
	hotkey: "p",
})

makeAnalyticsLayer({
	id: "dash",
	name: "Dashboard",
	symbol: "Dash",
	position: 1,
	row: 5,
	color: dataColors.visual,
	requires: new Decimal(2),
	resource: "dashboards",
	baseResource: "panels",
	baseAmount() {return layerPoints("panel")},
	boostedBy: ["sem"],
	branches: ["panel", "sem"],
	definition: "A dashboard assembles panels, filters, parameters, drill paths, access control, and refresh schedules.",
	flavor: "The surface is visual, but the product is a workflow for monitoring, diagnosis, and decision making.",
	effectDescription: "Dashboards multiply the finished analytics surface",
	upgradeTitle: "Crossfilter Interactions",
	upgradeDescription: "Use selections in one panel to filter related panels through shared dimensions.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Drill Paths",
	buyableResource: "drill paths",
	buyableBase: 2.5,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "The executive view finally respects the metric definitions.",
	hotkey: "b",
})

makeAnalyticsLayer({
	id: "simd",
	name: "SIMD Instruction",
	symbol: "SIMD",
	position: 2,
	row: 1,
	color: dataColors.execution,
	requires: new Decimal(4),
	resource: "SIMD instructions",
	baseResource: "typed tuples",
	baseAmount() {return layerPoints("tup")},
	boostedBy: ["vec", "exec"],
	branches: ["tup"],
	definition: "A SIMD instruction applies one operation across multiple data lanes in a CPU vector register.",
	flavor: "AVX, masks, gathers, shuffles, predicate vectors, and the cost of misaligned memory.",
	effectDescription: "SIMD instructions multiply tuple scanning",
	upgradeTitle: "Predicate Masks",
	upgradeDescription: "Represent filter results as lane masks so scans can avoid scalar branches.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Lanes",
	buyableResource: "lanes",
	buyableBase: 2,
	buyablePower: 1.2,
	milestoneAt: 8,
	milestoneText: "The CPU stops pretending scalar code was fine.",
	hotkey: "i",
})

makeAnalyticsLayer({
	id: "vec",
	name: "Column Vector",
	symbol: "Vec",
	position: 2,
	row: 2,
	color: dataColors.execution,
	requires: new Decimal(3),
	resource: "column vectors",
	baseResource: "SIMD instructions",
	baseAmount() {return layerPoints("simd")},
	boostedBy: ["exec"],
	branches: ["simd"],
	definition: "A column vector stores one field for many rows, usually with validity bitmaps and compact encodings.",
	flavor: "Columnar batches favor scans, compression, predicate pushdown, and vectorized execution.",
	effectDescription: "Column vectors multiply SIMD packing",
	upgradeTitle: "Arrow Buffers",
	upgradeDescription: "Separate values, offsets, and validity so columnar data can move across systems efficiently.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Cache Lines",
	buyableResource: "cache lines",
	buyableBase: 2.25,
	buyablePower: 1.1,
	milestoneAt: 6,
	milestoneText: "The memory hierarchy accepts your offering.",
	hotkey: "e",
})

makeAnalyticsLayer({
	id: "exec",
	name: "Vectorized Executor",
	symbol: "Exec",
	position: 2,
	row: 4,
	color: dataColors.execution,
	requires: new Decimal(2),
	resource: "executors",
	baseResource: "column vectors",
	baseAmount() {return layerPoints("vec")},
	boostedBy: ["opt", "db"],
	branches: ["vec", "opt", "db"],
	definition: "A vectorized executor evaluates physical plans in column batches instead of tuple-at-a-time loops.",
	flavor: "Tight loops, selection vectors, late materialization, fused kernels, and profiles full of cache misses.",
	effectDescription: "Executors multiply physical execution",
	upgradeTitle: "Late Materialization",
	upgradeDescription: "Do not fetch the expensive bytes until the predicate has earned them.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Operator Kernels",
	buyableResource: "operator kernels",
	buyableBase: 2.75,
	buyablePower: 1.3,
	milestoneAt: 3,
	milestoneText: "The plan is no longer interpreted; it is performed.",
	hotkey: "z",
})
