const dataColors = {
	primitive: "#F8F7F2",
	relational: "#8FD694",
	storage: "#5BC0EB",
	tableFormat: "#FACC15",
	network: "#F97316",
	optimizer: "#FDE74C",
	semantic: "#C084FC",
	visual: "#FF6B6B",
	execution: "#A7F3D0",
}

function layerPoints(layer) {
	if (!player[layer]) return new Decimal(0)
	return player[layer].points
}

function layerBoost(layer, power = 1) {
	return layerPoints(layer).add(10).log(10).pow(power)
}

function makeAnalyticsLayer(config) {
	const passiveRate = config.passiveGeneration || 0.001
	const passivePercent = passiveRate * 100
	const milestoneTarget = new Decimal(config.milestoneAt || 5).times(Decimal.pow(10, config.row + 1))
	const buyableCostScale = config.buyableCost || Decimal.pow(10, config.row + 1)
	const upgradeCostScale = config.upgradeCostScale || Decimal.pow(10, config.row + 1)
	let upgrades = {}
	if (config.upgradeTitle) {
		upgrades[11] = {
			title: config.upgradeTitle,
			description: config.upgradeDescription
				+ "<br><br>Effect: multiplies " + config.resource
				+ " gain based on your current " + config.resource + "."
				+ "<br><br>Also unlocks passive gain for this layer: " + passivePercent
				+ "% of reset gain per second.",
			cost: new Decimal(config.upgradeCost || 1).times(upgradeCostScale),
			effect() {
				return player[this.layer].points.add(1).ln().add(1).pow(config.upgradePower || 1)
			},
			effectDisplay() {return format(this.effect()) + "x " + config.resource + " gain"},
		}
	}

	let buyables = {}
	if (config.buyableTitle) {
		buyables[11] = {
			title: config.buyableTitle,
			cost(x) {
				return Decimal.pow(config.buyableBase || 2, x.add(1)).times(buyableCostScale).floor()
			},
			effect(x) {
				return x.add(1).pow(config.buyablePower || 1)
			},
			display() {
				return "You have " + getBuyableAmount(this.layer, this.id) + " " + config.buyableResource
					+ "<br><br>Effect: " + format(buyableEffect(this.layer, this.id)) + "x " + tmp[this.layer].resource + " gain"
					+ "<br><br>Cost: " + format(tmp[this.layer].buyables[this.id].cost) + " " + tmp[this.layer].resource
			},
			canAfford() {
				return player[this.layer].points.gte(tmp[this.layer].buyables[this.id].cost)
			},
			buy() {
				let cost = tmp[this.layer].buyables[this.id].cost
				player[this.layer].points = player[this.layer].points.sub(cost)
				setBuyableAmount(this.layer, this.id, getBuyableAmount(this.layer, this.id).add(1))
			},
		}
	}

	addLayer(config.id, {
		name: config.name,
		symbol: config.symbol,
		position: config.position,
		startData() { return {
			unlocked: true,
			points: new Decimal(0),
			best: new Decimal(0),
			total: new Decimal(0),
		}},
		color: config.color,
		requires: config.requires,
		resource: config.resource,
		baseResource: config.baseResource,
		baseAmount: config.baseAmount,
		type: config.type || "normal",
		exponent: config.exponent || 0.5,
		gainMult() {
			let mult = new Decimal(1)
			if (config.boostedBy) {
				for (let index = 0; index < config.boostedBy.length; index++) {
					mult = mult.times(layerBoost(config.boostedBy[index]))
				}
			}
			if (config.buyableTitle) mult = mult.times(buyableEffect(this.layer, 11))
			if (config.upgradeTitle && hasUpgrade(this.layer, 11)) mult = mult.times(upgradeEffect(this.layer, 11))
			return mult
		},
		gainExp() {
			return new Decimal(1)
		},
		effect() {
			let effect = player[this.layer].points.add(1).ln().add(1).pow(config.effectPower || 1)
			if (config.buyableTitle) effect = effect.times(buyableEffect(this.layer, 11))
			return effect
		},
		effectDescription() {
			return config.effectDescription + " by " + format(tmp[this.layer].effect) + "x"
		},
		passiveGeneration() {
			if (!tmp[config.id].baseAmount || tmp[config.id].baseAmount.lt(tmp[config.id].requires)) return new Decimal(0)
			if (!hasUpgrade(config.id, 11)) return new Decimal(0)
			return new Decimal(passiveRate)
		},
		row: config.row,
		branches: config.branches,
		layerShown() {
			if (config.row === 0) return true
			let data = player[config.id]
			if (data && (data.points.gt(0) || data.best.gt(0) || data.total.gt(0) || data.upgrades.length > 0)) return true
			return new Decimal(config.baseAmount()).gte(config.requires)
		},
		tooltip() {
			return formatWhole(player[this.layer].points) + " " + this.resource
		},
		tabFormat: [
			"main-display",
			["display-text", config.effectDescription + "."],
			["display-text", "Passive: buy this layer's upgrade to gain " + passivePercent + "% of reset gain each second while the reset requirement is met."],
			["blank", "8px"],
			"prestige-button",
			"resource-display",
			["blank", "12px"],
			["display-text", config.definition],
			["blank", "12px"],
			["display-text", config.flavor],
			["blank", "12px"],
			"buyables",
			["blank", "12px"],
			"upgrades",
			["blank", "12px"],
			"milestones",
		],
		upgrades,
		buyables,
		milestones: {
			0: {
				requirementDescription() {return formatWhole(milestoneTarget) + " " + config.resource},
				effectDescription: config.milestoneText,
				done() {return player[this.layer].best.gte(milestoneTarget)},
			},
		},
		hotkeys: config.hotkey ? [
			{
				key: config.hotkey,
				description: config.hotkey.toUpperCase() + ": reset for " + config.resource,
				onPress(){if (canReset(this.layer)) doReset(this.layer)},
			},
		] : [],
	})
}

makeAnalyticsLayer({
	id: "row",
	name: "Row",
	symbol: "Row",
	position: 0,
	row: 0,
	color: dataColors.primitive,
	requires: new Decimal(10),
	resource: "rows",
	baseResource: "events",
	baseAmount() {return player.points},
	boostedBy: ["rel", "alg", "stat", "viz", "simd"],
	definition: "A row is one event shaped into tabular form: values aligned to attributes and ready for analytics systems.",
	flavor: "Raw events become rows once ingestion assigns timestamps, identifiers, source names, and failure modes.",
	effectDescription: "Rows multiply event ingress",
	upgradeTitle: "Online Ingestion",
	upgradeDescription: "Continuously ingest event streams into rows instead of relying on manual batch resets.",
	upgradeCost: new Decimal(3),
	buyableTitle: "Typed Tuple",
	buyableResource: "typed tuples",
	buyableBase: 2,
	buyablePower: 0.75,
	milestoneAt: 10,
	milestoneText: "The warehouse admits that nullability is a social construct.",
	hotkey: "t",
})

makeAnalyticsLayer({
	id: "rel",
	name: "Relation",
	symbol: "Rel",
	position: 0,
	row: 1,
	color: dataColors.tableFormat,
	requires: new Decimal(4),
	resource: "relations",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["sch", "stat"],
	branches: ["row"],
	definition: "A relation is a set of tuples over named attributes, the formal core behind tables and query results.",
	flavor: "Codd removes physical row order and leaves keys, dependencies, joins, projection, and a lot of useful discipline.",
	effectDescription: "Relations multiply tuple normalization",
	upgradeTitle: "First Normal Form",
	upgradeDescription: "Ban nested attributes until the BI tool invents JSON columns again.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Candidate Keys",
	buyableResource: "candidate keys",
	buyableBase: 2.25,
	buyablePower: 0.8,
	milestoneAt: 8,
	milestoneText: "Projection and selection become first-class operations instead of spreadsheet habits.",
	hotkey: "r",
})

makeAnalyticsLayer({
	id: "sch",
	name: "Schema",
	symbol: "Sch",
	position: 0,
	row: 2,
	color: dataColors.storage,
	requires: new Decimal(3),
	resource: "schemas",
	baseResource: "relations",
	baseAmount() {return layerPoints("rel")},
	boostedBy: ["cat", "onto"],
	branches: ["rel"],
	definition: "A schema names relations, columns, data types, constraints, indexes, and ownership boundaries.",
	flavor: "DDL is where product assumptions become production contracts.",
	effectDescription: "Schemas multiply relation materialization",
	upgradeTitle: "Foreign Key Constraints",
	upgradeDescription: "Make relationships explicit enough for integrity checks, joins, and modeling tools to trust them.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Check Constraints",
	buyableResource: "check constraints",
	buyableBase: 2,
	buyablePower: 1.1,
	milestoneAt: 6,
	milestoneText: "Dimension tables become reusable instead of being rebuilt in every dashboard.",
	hotkey: "s",
})

makeAnalyticsLayer({
	id: "cat",
	name: "Catalog",
	symbol: "Catlg",
	position: 0,
	row: 3,
	color: dataColors.storage,
	requires: new Decimal(2),
	resource: "catalogs",
	baseResource: "schemas",
	baseAmount() {return layerPoints("sch")},
	boostedBy: ["db", "met", "sem"],
	branches: ["sch", "stat", "met", "sem"],
	definition: "A catalog stores metadata about schemas, tables, columns, indexes, statistics, privileges, and lineage.",
	flavor: "Catalog data is operational: query planners, governance tools, and BI explorers all depend on it.",
	effectDescription: "Catalogs multiply schema discovery",
	upgradeTitle: "Information Schema",
	upgradeDescription: "Expose standard metadata views so tools can discover tables without hand-maintained config.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Statistics Objects",
	buyableResource: "statistics objects",
	buyableBase: 2.5,
	buyablePower: 1,
	milestoneAt: 4,
	milestoneText: "The data dictionary becomes complete enough for humans and planners to use.",
	hotkey: "c",
})

makeAnalyticsLayer({
	id: "db",
	name: "Database",
	symbol: "DB",
	position: 0,
	row: 4,
	color: dataColors.storage,
	requires: new Decimal(2),
	resource: "databases",
	baseResource: "catalogs",
	baseAmount() {return layerPoints("cat")},
	boostedBy: ["fmt", "exec", "dist", "onto"],
	branches: ["cat", "fmt", "exec", "dist", "onto"],
	definition: "A database combines logical models with storage, transactions, indexes, catalogs, and execution engines.",
	flavor: "Relations are clean; databases add pages, locks, WAL, compaction, memory pressure, and operational reality.",
	effectDescription: "Databases multiply the whole storage spine",
	upgradeTitle: "MVCC Snapshots",
	upgradeDescription: "Serve consistent reads while writes continue, with vacuum debt waiting in the background.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Buffer Pages",
	buyableResource: "buffer pages",
	buyableBase: 3,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "Operational constraints now matter as much as logical correctness.",
	hotkey: "d",
})

makeAnalyticsLayer({
	id: "fmt",
	name: "Table Format",
	symbol: "Fmt",
	position: 1,
	row: 1,
	color: dataColors.storage,
	requires: new Decimal(2),
	resource: "table formats",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["stat", "flight", "db", "exec"],
	branches: ["row", "stat", "flight", "db", "exec"],
	definition: "A table format defines how rows are stored for analytics: files, row groups, column chunks, statistics, schema evolution, and snapshots.",
	flavor: "Parquet and ORC make scans cheap with column chunks and compression; Iceberg and Delta add manifests, snapshots, partitions, and commit protocols.",
	effectDescription: "Table formats multiply storage interoperability",
	upgradeTitle: "Predicate Pushdown",
	upgradeDescription: "Use row-group and column statistics to skip files, stripes, and pages before the executor reads bytes.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Row Group",
	buyableResource: "row groups",
	buyableBase: 2.5,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "Compression codecs and min/max stats become part of query planning.",
	hotkey: "g",
})

makeAnalyticsLayer({
	id: "alg",
	name: "Relational Algebra",
	symbol: "RA",
	position: -2,
	row: 1,
	color: dataColors.relational,
	requires: new Decimal(4),
	resource: "algebra terms",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["qry", "opt"],
	branches: ["row"],
	definition: "Relational algebra composes selection, projection, joins, union, difference, aggregation, and renaming.",
	flavor: "SQL gets lowered into algebra so equivalence rules can simplify and reorder work.",
	effectDescription: "Algebra terms multiply tuple rewriting",
	upgradeTitle: "Rename Operator",
	upgradeDescription: "Track attribute names through derived relations so later joins do not become ambiguous.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Join Trees",
	buyableResource: "join trees",
	buyableBase: 2.2,
	buyablePower: 0.9,
	milestoneAt: 8,
	milestoneText: "Selection pushdown removes rows before the expensive operators see them.",
	hotkey: "a",
})

makeAnalyticsLayer({
	id: "qry",
	name: "Query",
	symbol: "SQL",
	position: -2,
	row: 2,
	color: dataColors.relational,
	requires: new Decimal(3),
	resource: "queries",
	baseResource: "algebra terms",
	baseAmount() {return layerPoints("alg")},
	boostedBy: ["opt", "ds"],
	branches: ["alg"],
	definition: "A query describes the result relation while leaving access paths, join order, and physical operators open.",
	flavor: "The SELECT list reads like intent; the FROM clause determines whether the system has a long afternoon.",
	effectDescription: "Queries multiply algebra lowering",
	upgradeTitle: "Correlated Subquery",
	upgradeDescription: "Reference outer rows from inner expressions and give the optimizer a decorrelation problem.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Common Table Expressions",
	buyableResource: "CTEs",
	buyableBase: 2,
	buyablePower: 1,
	milestoneAt: 6,
	milestoneText: "Recursive CTEs become a sanctioned fixed point.",
	hotkey: "q",
})

makeAnalyticsLayer({
	id: "stat",
	name: "Table Statistics",
	symbol: "Stats",
	position: -1,
	row: 1,
	color: dataColors.optimizer,
	requires: new Decimal(4),
	resource: "histograms",
	baseResource: "table formats",
	baseAmount() {return layerPoints("fmt")},
	boostedBy: ["cat", "opt"],
	branches: ["fmt"],
	definition: "Table statistics summarize formatted storage: row-group counts, column distributions, null fractions, min/max ranges, and data skew.",
	flavor: "Histograms, most-common values, and distinct-count estimates are small summaries extracted from table files with large consequences.",
	effectDescription: "Histograms multiply tuple sampling",
	upgradeTitle: "NDV Estimator",
	upgradeDescription: "Count distinct values by not counting most of them.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Most Common Values",
	buyableResource: "MCV buckets",
	buyableBase: 2,
	buyablePower: 1.15,
	milestoneAt: 8,
	milestoneText: "The planner stops assuming uniform distributions for obviously skewed columns.",
	hotkey: "h",
})

makeAnalyticsLayer({
	id: "opt",
	name: "Query Optimizer",
	symbol: "Opt",
	position: 2,
	row: 4,
	color: dataColors.optimizer,
	requires: new Decimal(2),
	resource: "plans",
	baseResource: "executors",
	baseAmount() {return layerPoints("exec")},
	boostedBy: ["stat", "db", "fmt", "dist"],
	branches: ["exec", "stat", "db", "fmt", "dist"],
	definition: "A query optimizer searches equivalent logical plans and chooses physical operators using estimated cost.",
	flavor: "Executor feedback, dynamic programming, cardinality estimates, access paths, bushy joins, and one catastrophic nested loop.",
	effectDescription: "Plans multiply query execution",
	upgradeTitle: "Volcano Memo",
	upgradeDescription: "Memoize equivalent expressions so cost-based search can compare alternatives directly.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Join Reorderings",
	buyableResource: "join reorderings",
	buyableBase: 2.75,
	buyablePower: 1.05,
	milestoneAt: 4,
	milestoneText: "The optimizer learns to fear cross joins.",
	hotkey: "o",
})

makeAnalyticsLayer({
	id: "ds",
	name: "Data Set",
	symbol: "DS",
	position: -1,
	row: 3,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "data sets",
	baseResource: "queries",
	baseAmount() {return layerPoints("qry")},
	boostedBy: ["met", "viz"],
	branches: ["qry"],
	definition: "A data set is a governed query result with lineage, freshness, owners, documentation, and consumers.",
	flavor: "It is not just a table; it is a reusable contract for downstream analytics.",
	effectDescription: "Data sets multiply query reuse",
	upgradeTitle: "Column Lineage",
	upgradeDescription: "Trace output fields back through transforms so ownership and impact analysis are possible.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Materializations",
	buyableResource: "materializations",
	buyableBase: 2.25,
	buyablePower: 1.1,
	milestoneAt: 4,
	milestoneText: "Freshness SLAs become visible enough to be enforced.",
	hotkey: "x",
})

makeAnalyticsLayer({
	id: "met",
	name: "Metric",
	symbol: "Met",
	position: -1,
	row: 4,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "metrics",
	baseResource: "data sets",
	baseAmount() {return layerPoints("ds")},
	boostedBy: ["cat", "onto", "sem"],
	branches: ["ds", "cat"],
	definition: "A metric defines a measure, grain, filters, valid dimensions, owner, freshness target, and business meaning.",
	flavor: "Revenue, conversion, churn, retention, active users: each is a query plus a contract about how it may be grouped.",
	effectDescription: "Metrics multiply semantic compilation",
	upgradeTitle: "Metric Contract",
	upgradeDescription: "Define grain, filters, owners, allowed dimensions, and freshness expectations for each measure.",
	upgradeCost: new Decimal(1),
	buyableTitle: "KPI Definitions",
	buyableResource: "KPI definitions",
	buyableBase: 2.5,
	buyablePower: 1.25,
	milestoneAt: 3,
	milestoneText: "The model starts rejecting contradictory KPI definitions.",
	hotkey: "m",
})

makeAnalyticsLayer({
	id: "sem",
	name: "Semantic Layer",
	symbol: "Sem",
	position: -1,
	row: 5,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "semantic layers",
	baseResource: "metrics",
	baseAmount() {return layerPoints("met")},
	boostedBy: ["cat", "dash", "onto"],
	branches: ["met", "cat"],
	definition: "A semantic layer exposes governed metrics, dimensions, permissions, and SQL generation across tools.",
	flavor: "It turns agreed metric contracts into reusable queries for dashboards, notebooks, APIs, and downstream ontology mappings.",
	effectDescription: "Semantic layers multiply dashboard correctness",
	upgradeTitle: "Semantic Compilation",
	upgradeDescription: "Compile metrics, dimensions, access policies, and SQL dialect rules into queryable models.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Business Terms",
	buyableResource: "business terms",
	buyableBase: 2,
	buyablePower: 1.35,
	milestoneAt: 3,
	milestoneText: "Self-service analytics briefly means what it says.",
	hotkey: "l",
})

makeAnalyticsLayer({
	id: "onto",
	name: "Enterprise Ontology",
	symbol: "OWL",
	position: -1,
	row: 7,
	color: dataColors.semantic,
	requires: new Decimal(2),
	resource: "ontologies",
	baseResource: "semantic layers",
	baseAmount() {return layerPoints("sem")},
	boostedBy: ["db", "dist", "dash"],
	branches: ["sem", "sch", "db", "dist"],
	definition: "An enterprise ontology specifies exchange semantics for systems, links, information specs, functions, organizations, facilities, and architecture metadata.",
	flavor: "RDF triples carry identifiers; OWL axioms constrain meaning; temporal parts track change without pretending a renamed system is a new thing.",
	effectDescription: "Ontologies multiply semantic interoperability",
	upgradeTitle: "4D Extensional Identity",
	upgradeDescription: "Identify entities by their physical and temporal extent, so names, versions, ownership, and classifications can change without losing identity.",
	upgradeCost: new Decimal(1),
	buyableTitle: "RDF/OWL Axioms",
	buyableResource: "RDF/OWL axioms",
	buyableBase: 2.5,
	buyablePower: 1.3,
	milestoneAt: 3,
	milestoneText: "Architecture metadata, information specifications, systems, and activities share exchange semantics.",
	hotkey: "n",
})

makeAnalyticsLayer({
	id: "viz",
	name: "Visualization Grammar",
	symbol: "Viz",
	position: 1,
	row: 1,
	color: dataColors.visual,
	requires: new Decimal(4),
	resource: "marks",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["panel", "dash"],
	branches: ["row"],
	definition: "A visualization grammar maps fields to marks, channels, scales, guides, facets, transforms, and layouts.",
	flavor: "Vega-Lite, ggplot, and similar grammars make chart construction explicit enough to reason about.",
	effectDescription: "Marks multiply visual encoding",
	upgradeTitle: "Grammar of Graphics",
	upgradeDescription: "Separate data, encodings, marks, statistical transforms, scales, coordinates, and guides.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Scales",
	buyableResource: "scales",
	buyableBase: 2,
	buyablePower: 0.95,
	milestoneAt: 8,
	milestoneText: "Axes stop lying unless explicitly configured to lie.",
	hotkey: "v",
})

makeAnalyticsLayer({
	id: "panel",
	name: "Panel",
	symbol: "Panel",
	position: 1,
	row: 3,
	color: dataColors.visual,
	requires: new Decimal(2),
	resource: "panels",
	baseResource: "marks",
	baseAmount() {return layerPoints("viz")},
	boostedBy: ["dash"],
	branches: ["viz", "ds"],
	definition: "A panel combines one visual, its query, thresholds, filters, title, layout, and interaction state.",
	flavor: "Panel design is where chart grammar meets dashboard review, alert thresholds, and limited screen space.",
	effectDescription: "Panels multiply mark composition",
	upgradeTitle: "Small Multiples",
	upgradeDescription: "Repeat the same visual across dimension values for comparison without changing encodings.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Encodings",
	buyableResource: "encodings",
	buyableBase: 2.4,
	buyablePower: 1.15,
	milestoneAt: 4,
	milestoneText: "Tooltips acquire a type system.",
	hotkey: "p",
})

makeAnalyticsLayer({
	id: "dash",
	name: "Dashboard",
	symbol: "Dash",
	position: 1,
	row: 6,
	color: dataColors.visual,
	requires: new Decimal(2),
	resource: "dashboards",
	baseResource: "panels",
	baseAmount() {return layerPoints("panel")},
	boostedBy: ["sem", "dist"],
	branches: ["panel", "sem", "dist"],
	definition: "A dashboard assembles panels, filters, parameters, drill paths, access control, and refresh schedules.",
	flavor: "The surface is visual, but the product is a workflow for monitoring, diagnosis, and decision making.",
	effectDescription: "Dashboards multiply the finished analytics surface",
	upgradeTitle: "Crossfilter Interactions",
	upgradeDescription: "Use selections in one panel to filter related panels through shared dimensions.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Drill Paths",
	buyableResource: "drill paths",
	buyableBase: 2.5,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "The executive view finally respects the metric definitions.",
	hotkey: "b",
})

makeAnalyticsLayer({
	id: "simd",
	name: "SIMD Instruction",
	symbol: "SIMD",
	position: 2,
	row: 1,
	color: dataColors.execution,
	requires: new Decimal(4),
	resource: "SIMD instructions",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["vec", "exec"],
	branches: ["row"],
	definition: "A SIMD instruction applies one operation across multiple data lanes in a CPU vector register.",
	flavor: "AVX, masks, gathers, shuffles, predicate vectors, and the cost of misaligned memory.",
	effectDescription: "SIMD instructions multiply tuple scanning",
	upgradeTitle: "Predicate Masks",
	upgradeDescription: "Represent filter results as lane masks so scans can avoid scalar branches.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Lanes",
	buyableResource: "lanes",
	buyableBase: 2,
	buyablePower: 1.2,
	milestoneAt: 8,
	milestoneText: "The CPU stops pretending scalar code was fine.",
	hotkey: "i",
})

makeAnalyticsLayer({
	id: "vec",
	name: "Column Vector",
	symbol: "Vec",
	position: 2,
	row: 2,
	color: dataColors.execution,
	requires: new Decimal(3),
	resource: "column vectors",
	baseResource: "SIMD instructions",
	baseAmount() {return layerPoints("simd")},
	boostedBy: ["exec"],
	branches: ["simd"],
	definition: "A column vector stores one field for many rows, usually with validity bitmaps and compact encodings.",
	flavor: "Columnar batches favor scans, compression, predicate pushdown, and vectorized execution.",
	effectDescription: "Column vectors multiply SIMD packing",
	upgradeTitle: "Arrow Buffers",
	upgradeDescription: "Separate values, offsets, and validity so columnar data can move across systems efficiently.",
	upgradeCost: new Decimal(2),
	buyableTitle: "Cache Lines",
	buyableResource: "cache lines",
	buyableBase: 2.25,
	buyablePower: 1.1,
	milestoneAt: 6,
	milestoneText: "The memory hierarchy accepts your offering.",
	hotkey: "e",
})

makeAnalyticsLayer({
	id: "exec",
	name: "Vectorized Executor",
	symbol: "Exec",
	position: -2,
	row: 3,
	color: dataColors.execution,
	requires: new Decimal(2),
	resource: "executors",
	baseResource: "queries and column vectors",
	baseAmount() {return layerPoints("qry").min(layerPoints("vec"))},
	boostedBy: ["opt", "db", "fmt", "dist"],
	branches: ["qry", "vec", "opt", "db", "fmt", "dist"],
	definition: "A vectorized executor evaluates queries in column batches instead of tuple-at-a-time loops.",
	flavor: "Tight loops, selection vectors, late materialization, fused kernels, and runtime feedback for the optimizer.",
	effectDescription: "Executors multiply physical execution",
	upgradeTitle: "Late Materialization",
	upgradeDescription: "Do not fetch the expensive bytes until the predicate has earned them.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Operator Kernels",
	buyableResource: "operator kernels",
	buyableBase: 2.75,
	buyablePower: 1.3,
	milestoneAt: 3,
	milestoneText: "The plan is no longer interpreted; it is performed.",
	hotkey: "z",
})

makeAnalyticsLayer({
	id: "net",
	name: "Network Link",
	symbol: "Net",
	position: 2,
	row: 1,
	color: dataColors.network,
	requires: new Decimal(2),
	resource: "network links",
	baseResource: "rows",
	baseAmount() {return layerPoints("row")},
	boostedBy: ["flight", "dist"],
	branches: ["row", "flight", "dist"],
	definition: "A network link is the primitive transport path for data: endpoints, packets, latency, bandwidth, loss, and routing.",
	flavor: "Before clusters coordinate, bytes cross links with timeouts, retries, congestion, backpressure, and inconvenient packet loss.",
	effectDescription: "Network links multiply data movement",
	upgradeTitle: "Flow Control",
	upgradeDescription: "Apply windows, acknowledgements, retries, and backpressure so fast senders do not overwhelm receivers.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Communication Link",
	buyableResource: "communication links",
	buyableBase: 2.75,
	buyablePower: 1.2,
	milestoneAt: 3,
	milestoneText: "Timeouts become configuration, not folklore.",
	hotkey: "w",
})

makeAnalyticsLayer({
	id: "flight",
	name: "Flight Protocol",
	symbol: "Flight",
	position: 2,
	row: 2,
	color: dataColors.network,
	requires: new Decimal(2),
	resource: "Flight protocols",
	baseResource: "table formats and network links",
	baseAmount() {return layerPoints("fmt").min(layerPoints("net"))},
	boostedBy: ["dist"],
	branches: ["fmt", "net", "dist"],
	definition: "A Flight-style protocol combines columnar table formats with network transport for high-throughput data exchange.",
	flavor: "Schema, record batches, endpoints, tickets, streams, and backpressure turn stored columns into network-native analytics payloads.",
	effectDescription: "Flight protocols multiply table transport",
	upgradeTitle: "Columnar RPC",
	upgradeDescription: "Move typed record batches over long-lived streams instead of serializing rows one request at a time.",
	upgradeCost: new Decimal(1),
	buyableTitle: "Record Batch Stream",
	buyableResource: "record batch streams",
	buyableBase: 2.75,
	buyablePower: 1.25,
	milestoneAt: 3,
	milestoneText: "Table format and transport agree on schema, batches, and flow control.",
	hotkey: "y",
})

makeAnalyticsLayer({
	id: "dist",
	name: "Distributed System",
	symbol: "CAP",
	position: 2,
	row: 6,
	color: dataColors.execution,
	requires: new Decimal(2),
	resource: "distributed systems",
	baseResource: "Flight protocols and executors",
	baseAmount() {return layerPoints("flight").min(layerPoints("exec"))},
	boostedBy: ["dash", "onto"],
	branches: ["flight", "exec", "dash", "onto"],
	definition: "A distributed system coordinates Flight-style data exchange and distributed compute across membership, scheduling, replication, failure detection, and recovery.",
	flavor: "CAP theorem frames the hard choice during partitions; MapReduce jobs run inside the cluster as distributed batch execution.",
	effectDescription: "Distributed systems multiply cluster-scale analytics",
	upgradeTitle: "Consensus Log",
	upgradeDescription: "Use replicated logs, leader election, and quorum acknowledgements to keep nodes ordered through failures.",
	upgradeCost: new Decimal(1),
	buyableTitle: "MapReduce Job",
	buyableResource: "MapReduce jobs",
	buyableBase: 3,
	buyablePower: 1.25,
	milestoneAt: 3,
	milestoneText: "Shuffle partitioning and straggler mitigation become part of distributed execution.",
	hotkey: "u",
})
